/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java_petri_net;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author caparies
 */
public class Petrinet_Specialists extends javax.swing.JFrame {

    /**
     * Creates new form Petrinet_Specialists
     */
    public Petrinet_Specialists() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        change.setBorder(border);
        end.setBorder(border);
        start.setBorder(border);
    }
    
    // global variable
    int Wait = 0;
    int Free = 0;
    int Busy = 0;
    int Inside = 0;
    int Docu = 0;
    int Done = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void check_transition(){
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        docu_text = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        free = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        docu = new javax.swing.JLabel();
        autofire = new javax.swing.JButton();
        wait = new javax.swing.JLabel();
        busy = new javax.swing.JLabel();
        done = new javax.swing.JLabel();
        inside = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        setToken = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        free_text = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inside_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        busy_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        waitplace = new javax.swing.JLabel();
        freeplace = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insideplace = new javax.swing.JLabel();
        doneplace = new javax.swing.JLabel();
        busyplace = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        done_text = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        wait_text = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("Change");

        docu_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docu_textActionPerformed(evt);
            }
        });
        docu_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docu_textKeyTyped(evt);
            }
        });

        jLabel14.setText("Done");

        free.setText("0");

        jLabel15.setText("Inside");

        docu.setText("0");

        autofire.setText("Auto fire");
        autofire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autofireActionPerformed(evt);
            }
        });

        wait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wait.setText("0");

        busy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busy.setText("0");

        done.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        done.setText("0");

        inside.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inside.setText("0");

        end.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        end.setForeground(new java.awt.Color(24, 30, 40));
        end.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        end.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(35, 41, 52))); // NOI18N
        end.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        end.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                endMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                endMouseExited(evt);
            }
        });

        start.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        start.setForeground(new java.awt.Color(24, 30, 40));
        start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(35, 41, 52))); // NOI18N
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
        });

        jLabel16.setText("Wait");

        setToken.setText("Set token");
        setToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTokenActionPerformed(evt);
            }
        });

        jLabel17.setText("Free");

        free_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                free_textActionPerformed(evt);
            }
        });
        free_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                free_textKeyTyped(evt);
            }
        });

        jLabel18.setText("Inside");

        jLabel7.setText("Free");

        inside_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inside_textActionPerformed(evt);
            }
        });
        inside_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inside_textKeyTyped(evt);
            }
        });

        jLabel8.setText("Docu");

        busy_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busy_textActionPerformed(evt);
            }
        });
        busy_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busy_textKeyTyped(evt);
            }
        });

        jLabel9.setText("End");

        jLabel10.setText("Wait");

        waitplace.setFont(new java.awt.Font("Hack Nerd Font", 0, 48)); // NOI18N
        waitplace.setText("");

        freeplace.setFont(new java.awt.Font("Hack Nerd Font", 0, 48)); // NOI18N
        freeplace.setText("");

        jLabel3.setFont(new java.awt.Font("Hack Nerd Font", 0, 48)); // NOI18N
        jLabel3.setText("");

        insideplace.setFont(new java.awt.Font("Hack Nerd Font", 0, 48)); // NOI18N
        insideplace.setText("");

        doneplace.setFont(new java.awt.Font("Hack Nerd Font", 0, 48)); // NOI18N
        doneplace.setText("");

        busyplace.setFont(new java.awt.Font("Hack Nerd Font", 0, 48)); // NOI18N
        busyplace.setText("");

        change.setFont(new java.awt.Font("Hack Nerd Font", 1, 24)); // NOI18N
        change.setForeground(new java.awt.Color(24, 30, 40));
        change.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        change.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(35, 41, 52))); // NOI18N
        change.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeMouseExited(evt);
            }
        });

        jLabel19.setText("Busy");

        jLabel20.setText("Done");

        jLabel11.setText("Start");

        done_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_textActionPerformed(evt);
            }
        });
        done_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                done_textKeyTyped(evt);
            }
        });

        jLabel12.setText("Busy");

        jLabel21.setText("Docu");

        wait_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wait_textActionPerformed(evt);
            }
        });
        wait_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wait_textKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busy_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wait_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(free_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(done_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docu_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inside_text, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(doneplace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(wait, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(waitplace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(setToken)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(autofire)
                            .addGap(19, 19, 19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(free, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9)
                                            .addGap(94, 94, 94))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(91, 91, 91)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(insideplace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(busyplace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel15)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(busy, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(inside, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                .addComponent(freeplace, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(81, 81, 81)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(docu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneplace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(done)
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(free_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(inside_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wait_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(done_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(busy_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docu_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(freeplace, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(end, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(free))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(docu)))
                    .addGap(60, 60, 60)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(busyplace)
                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(waitplace))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(busy)
                                .addComponent(wait)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13))))
                    .addGap(37, 37, 37)
                    .addComponent(jLabel15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(insideplace)
                    .addGap(1, 1, 1)
                    .addComponent(inside)
                    .addGap(113, 113, 113)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setToken)
                        .addComponent(autofire))
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseClicked
        // TODO add your handling code here:
        Busy = Integer.parseInt(busy.getText());
        Inside = Integer.parseInt(inside.getText());
        if(Busy > 0 && Inside > 0){
            Busy --;
            Inside --;
            Done ++;
            Docu ++;
            docu.setText(String.valueOf(Docu));
            done.setText(String.valueOf(Done));
            inside.setText(String.valueOf(Inside));
            busy.setText(String.valueOf(Busy));
        }
        
    }//GEN-LAST:event_changeMouseClicked

    private void changeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseEntered
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        change.setBorder(border);
        change.setForeground(Color.white);
    }//GEN-LAST:event_changeMouseEntered

    private void changeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseExited
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        change.setBorder(border);
        change.setForeground(Color.black);
    }//GEN-LAST:event_changeMouseExited

    private void endMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endMouseClicked
        // TODO add your handling code here:
        Docu = Integer.parseInt(docu.getText());
        if(Docu > 0){
            Docu --;
            Free ++;
            docu.setText(String.valueOf(Docu));
            free.setText(String.valueOf(Free));
            docu.setText(String.valueOf(Docu));
        }
    }//GEN-LAST:event_endMouseClicked

    private void endMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endMouseEntered
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        end.setBorder(border);
        end.setForeground(Color.white);
    }//GEN-LAST:event_endMouseEntered

    private void endMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endMouseExited
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        end.setBorder(border);
        end.setForeground(Color.black);
    }//GEN-LAST:event_endMouseExited

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
        Wait = Integer.parseInt(wait.getText());
        Free = Integer.parseInt(free.getText());
        if(Wait > 0 && Free > 0){
            Wait --;
            Free --;
            Busy ++;
            Inside ++;
            inside.setText(String.valueOf(Inside));
            busy.setText(String.valueOf(Busy));
            wait.setText(String.valueOf(Wait));
            free.setText(String.valueOf(Free));
        }
        
    }//GEN-LAST:event_startMouseClicked

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.white);
        start.setBorder(border);
        start.setForeground(Color.white);
    }//GEN-LAST:event_startMouseEntered

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
        // TODO add your handling code here:
        Border border = BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        start.setBorder(border);
        start.setForeground(Color.black);
    }//GEN-LAST:event_startMouseExited

    private void free_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_free_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_free_textActionPerformed

    private void inside_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inside_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inside_textActionPerformed

    private void busy_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busy_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busy_textActionPerformed

    private void done_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_done_textActionPerformed

    private void docu_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docu_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docu_textActionPerformed

    private void wait_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wait_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wait_textActionPerformed

    private void setTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTokenActionPerformed
        Wait = Integer.parseInt(wait_text.getText());
        Busy = Integer.parseInt(busy_text.getText());
        Free = Integer.parseInt(free_text.getText());
        Inside = Integer.parseInt(inside_text.getText());
        Docu = Integer.parseInt(docu_text.getText());
        Done = Integer.parseInt(done_text.getText());
        
        inside.setText(String.valueOf(Inside));
        busy.setText(String.valueOf(Busy));
        free.setText(String.valueOf(Free));
        wait.setText(String.valueOf(Wait));
        docu.setText(String.valueOf(Docu));
        done.setText(String.valueOf(Done));
        
    
        
        
    }//GEN-LAST:event_setTokenActionPerformed

    private void wait_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wait_textKeyTyped
        // allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_wait_textKeyTyped

    private void busy_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busy_textKeyTyped
        // allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_busy_textKeyTyped

    private void free_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_free_textKeyTyped
        // allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_free_textKeyTyped

    private void done_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_done_textKeyTyped
        // allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_done_textKeyTyped

    private void inside_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inside_textKeyTyped
        // allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_inside_textKeyTyped

    private void docu_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docu_textKeyTyped
        // allow only number
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_docu_textKeyTyped

    private void autofireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autofireActionPerformed
        // TODO add your handling code here:
        Boolean found = true;
        while(found){
            while(Docu > 0){
                Docu --;
                Free ++;
                docu.setText(String.valueOf(Docu));
                free.setText(String.valueOf(Free));
                try {
                    sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Petrinet_Specialists.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            while(Free > 0 && Wait > 0){    
                Wait --;
                Free --;
                Busy ++;
                Inside ++;
                inside.setText(String.valueOf(Inside));
                busy.setText(String.valueOf(Busy));
                wait.setText(String.valueOf(Wait));
                free.setText(String.valueOf(Free));
            }
            
            while(Busy > 0 && Inside > 0){
                Busy --;
                Inside --;
                Done ++;
                Docu ++;
                docu.setText(String.valueOf(Docu));
                done.setText(String.valueOf(Done));
                inside.setText(String.valueOf(Inside));
                busy.setText(String.valueOf(Busy));
            }
            if(Docu == 0) found = false;
        }
    }//GEN-LAST:event_autofireActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Specialists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Specialists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Specialists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petrinet_Specialists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petrinet_Specialists().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autofire;
    private javax.swing.JLabel busy;
    private javax.swing.JTextField busy_text;
    private javax.swing.JLabel busyplace;
    private javax.swing.JLabel change;
    private javax.swing.JLabel docu;
    private javax.swing.JTextField docu_text;
    private javax.swing.JLabel done;
    private javax.swing.JTextField done_text;
    private javax.swing.JLabel doneplace;
    private javax.swing.JLabel end;
    private javax.swing.JLabel free;
    private javax.swing.JTextField free_text;
    private javax.swing.JLabel freeplace;
    private javax.swing.JLabel inside;
    private javax.swing.JTextField inside_text;
    private javax.swing.JLabel insideplace;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton setToken;
    private javax.swing.JLabel start;
    private javax.swing.JLabel wait;
    private javax.swing.JTextField wait_text;
    private javax.swing.JLabel waitplace;
    // End of variables declaration//GEN-END:variables
}
